//Search musica/artista
export const SEARCH_FETCH_REQUEST = 'SEARCH_FETCH_REQUEST'
export const SEARCH_FETCH_SUCCEEDED = 'SEARCH_FETCH_SUCCEEDED'
export const SEARCH_FETCH_FAILURE = 'SEARCH_FETCH_FAILURE'
export const SEARCH_SESSION_EXPIRES = 'SEARCH_SESSION_EXPIRES'

export const ID_PLAYLIST_ALBUM = 'ID_PLAYLIST_ALBUM'
